# Generated by Django 5.2.7 on 2025-11-06 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransporterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("mini", "Mini Vehicle (30-300 kg)"),
                            ("lcv", "LCV (300-1000 kg)"),
                            ("mcv", "MCV (1000-5000 kg)"),
                            ("hcv", "HCV (5000-16000 kg)"),
                            ("trailer", "Trailer (16000-35000 kg)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transporter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transporter Profile",
                "verbose_name_plural": "Transporter Profiles",
            },
        ),
    ]
