# Generated by Django 5.2.7 on 2025-11-06 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("license_number", models.CharField(max_length=20)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("mini", "Mini Vehicle (30-300 kg)"),
                            ("lcv", "LCV (300-1000 kg)"),
                            ("mcv", "MCV (1000-5000 kg)"),
                            ("hcv", "HCV (5000-16000 kg)"),
                            ("trailer", "Trailer (16000-35000 kg)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=20)),
                ("vehicle_capacity", models.CharField(max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_online", models.BooleanField(default=False)),
                ("total_deliveries", models.IntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("rating", models.FloatField(default=5.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
